In [30]:
import pandas as pd
import numpy as np
import scipy as sps


from sklearn.metrics import roc_auc_score

def auc_weighted(y_true, y_pred):
    score = roc_auc_score(y_true, y_pred, average='weighted')
    return score


traindata = pd.read_csv("input_train.csv", delimiter=",")
output = pd.read_csv("output_train.csv", delimiter=";")
input_test = pd.read_csv("input_test.csv", delimiter=",")

In [5]:
traindata['SHIPPING_PRICE'] = traindata['SHIPPING_PRICE'].map({'<1': 0, '1<5':1, '5<10':2, '10<20':3, '>20': 4})
traindata['SHIPPING_PRICE'] = traindata['SHIPPING_PRICE'].fillna(0)

traindata['WARRANTIES_PRICE'] = traindata['WARRANTIES_PRICE'].map({'<5': 1, '5<20':2, '20<50':3, '50<100':4, '100<500':5})
traindata['WARRANTIES_PRICE'] = traindata['WARRANTIES_PRICE'].fillna(0)

traindata['PRICECLUB_STATUS'] = traindata['PRICECLUB_STATUS'].fillna("UNSUBSCRIBED")

traindata['PURCHASE_COUNT'] = traindata['PURCHASE_COUNT'].map({'<5':0, '5<20': 1, '20<50':2, '50<100':3, '100<500': 4, '>500':5})

traindata['BUYING_DATE'] = traindata['BUYING_DATE'].map({'1/2017':1, '2/2017':2,'3/2017':3,'4/2017':4,'5/2017':5, '6/2017':6, '7/2017':7, '8/2017':8, '9/2017':9, '10/2017':10})

traindata['SELLER_SCORE_COUNT'] = traindata['SELLER_SCORE_COUNT'].map({'<100':0, '100<1000':1, '1000<10000':2, '10000<100000':3, '100000<1000000':4})
traindata['SELLER_SCORE_COUNT'] = traindata['SELLER_SCORE_COUNT'].fillna(0)

traindata['SELLER_SCORE_AVERAGE'] = traindata['SELLER_SCORE_AVERAGE'].fillna(44)

traindata['ITEM_PRICE'] = traindata['ITEM_PRICE'].map({'<10':0, '10<20':1, '20<50':2, '50<100':3, '100<500':4, '500<1000':5, '1000<5000':6,'>5000':7})

In [6]:
traindata.describe()

,ID,SHIPPING_PRICE,WARRANTIES_PRICE,CARD_PAYMENT,COUPON_PAYMENT,RSP_PAYMENT,WALLET_PAYMENT,REGISTRATION_DATE,PURCHASE_COUNT,BUYER_BIRTHDAY_DATE,BUYER_DEPARTMENT,BUYING_DATE,SELLER_SCORE_COUNT,SELLER_SCORE_AVERAGE,SELLER_DEPARTMENT,ITEM_PRICE
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.00000,94164.000000,100000.000000,100000.000000,99994.000000,99994.000000,100000.000000,100000.000000
mean,49999.500000,0.363760,0.052140,0.895930,0.057290,0.170580,0.129550,2012.595230,1.40017,1976.129912,54.280890,5.384860,2.711873,45.850731,32.670560,1.027210
std,28867.657797,0.696235,0.323237,0.305353,0.232397,0.376143,0.335809,4.201691,1.57416,14.127001,27.864038,2.891029,1.029044,2.506009,35.006913,1.363066
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2001.000000,0.00000,1900.000000,-1.000000,1.000000,0.000000,10.000000,-1.000000,0.000000
25%,24999.750000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,2010.000000,0.00000,1967.000000,32.000000,3.000000,2.000000,45.000000,-1.000000,0.000000
50%,49999.500000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,2014.000000,1.00000,1977.000000,59.000000,5.000000,3.000000,46.000000,22.000000,0.000000
75%,74999.250000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,2016.000000,3.00000,1987.000000,77.000000,8.000000,4.000000,47.000000,70.000000,2.000000
max,99999.000000,4.000000,5.000000,1.000000,1.000000,1.000000,1.000000,2017.000000,5.00000,2016.000000,98.000000,10.000000,4.000000,50.000000,98.000000,7.000000